package com.wang.entity;
// Generated 2016-2-21 21:33:34 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbComment generated by hbm2java
 */
@Entity
@Table(name = "tb_comment", catalog = "micro_service")
public class TbComment implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long contentId;
	private Byte contentType;
	private String content;
	private Byte degree;
	private Date createTime;

	public TbComment() {
	}

	public TbComment(Long userId, Long contentId, Byte contentType, String content, Byte degree, Date createTime) {
		this.userId = userId;
		this.contentId = contentId;
		this.contentType = contentType;
		this.content = content;
		this.degree = degree;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "content_id")
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}

	@Column(name = "content_type")
	public Byte getContentType() {
		return this.contentType;
	}

	public void setContentType(Byte contentType) {
		this.contentType = contentType;
	}

	@Column(name = "content", length = 1024)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "degree")
	public Byte getDegree() {
		return this.degree;
	}

	public void setDegree(Byte degree) {
		this.degree = degree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
