package com.wang.entity;
// Generated 2016-2-21 21:33:34 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMessage generated by hbm2java
 */
@Entity
@Table(name = "tb_message", catalog = "micro_service")
public class TbMessage implements java.io.Serializable {

	private Long id;
	private Long senderId;
	private Long accepterId;
	private String content;
	private Date createTime;
	private Long contentId;
	private Byte contentType;

	public TbMessage() {
	}

	public TbMessage(Long senderId, Long accepterId, String content, Date createTime, Long contentId,
			Byte contentType) {
		this.senderId = senderId;
		this.accepterId = accepterId;
		this.content = content;
		this.createTime = createTime;
		this.contentId = contentId;
		this.contentType = contentType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "sender_id")
	public Long getSenderId() {
		return this.senderId;
	}

	public void setSenderId(Long senderId) {
		this.senderId = senderId;
	}

	@Column(name = "accepter_id")
	public Long getAccepterId() {
		return this.accepterId;
	}

	public void setAccepterId(Long accepterId) {
		this.accepterId = accepterId;
	}

	@Column(name = "content", length = 1024)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "content_id")
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}

	@Column(name = "content_type")
	public Byte getContentType() {
		return this.contentType;
	}

	public void setContentType(Byte contentType) {
		this.contentType = contentType;
	}

}
