package com.wang.entity;
// Generated 2016-2-21 21:33:34 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbRequireAttach generated by hbm2java
 */
@Entity
@Table(name = "tb_require_attach", catalog = "micro_service")
public class TbRequireAttach implements java.io.Serializable {

	private Long id;
	private Long requireId;
	private Byte type;
	private String name;
	private String path;

	public TbRequireAttach() {
	}

	public TbRequireAttach(Long requireId, Byte type, String name, String path) {
		this.requireId = requireId;
		this.type = type;
		this.name = name;
		this.path = path;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "require_id")
	public Long getRequireId() {
		return this.requireId;
	}

	public void setRequireId(Long requireId) {
		this.requireId = requireId;
	}

	@Column(name = "type")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
