package com.wang.entity;
// Generated 2016-2-21 21:33:34 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbRequire generated by hbm2java
 */
@Entity
@Table(name = "tb_require", catalog = "micro_service")
public class TbRequire implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String title;
	private String description;
	private Long good;
	private Long bad;
	private Byte type;
	private Date createTime;
	private Date beginTime;
	private Date endTime;
	private Long categoryId;
	private String tagId;
	private Byte status;





	public TbRequire() {
	}

	public TbRequire(Long userId, String title, String description, Long good, Long bad, Byte type, Date createTime,
			Date beginTime, Date endTime, Long categoryId, String tagId, Byte status) {
		this.userId = userId;
		this.title = title;
		this.description = description;
		this.good = good;
		this.bad = bad;
		this.type = type;
		this.createTime = createTime;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.categoryId = categoryId;
		this.tagId = tagId;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "good")
	public Long getGood() {
		return this.good;
	}

	public void setGood(Long good) {
		this.good = good;
	}

	@Column(name = "bad")
	public Long getBad() {
		return this.bad;
	}

	public void setBad(Long bad) {
		this.bad = bad;
	}

	@Column(name = "type")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_time", length = 19)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "category_id")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "tag_id")
	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
